In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("Restaurant_Reviews.tsv" ,  delimiter = '\t' , quoting = 3)
Data = np.matrix(dataset)
dataset

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
5       Now I am getting angry and I want my damn pho.      0
6                Honeslty it didn't taste THAT fresh.)      0
7    The potatoes were like rubber and you could te...      0
8                            The fries were great too.      1
9                                       A great touch.      1
10                            Service was very prompt.      1
11                                  Would not go back.      0
12   The cashier had no care what so ever on what I...      0
13   I tried the Cape Cod ravoli, chicken, with cra...      1
14   I was disgusted because I was pretty sure that...      0
15   I was shocked because no signs indicate cash o...      0
16                                 Highly recommended.      1
17              Waitress was a little slow in service.      0
18   This place is not worth your time, let alone V...      0
19                                did not like at all.      0
20                                 The Burrittos Blah!      0
21                                  The food, amazing.      1
22                               Service is also cute.      1
23   I could care less... The interior is just beau...      1
24                                  So they performed.      1
25   That's right....the red velvet cake.....ohhh t...      1
26          - They never brought a salad we asked for.      0
27   This hole in the wall has great Mexican street...      1
28   Took an hour to get our food only 4 tables in ...      0
29                   The worst was the salmon sashimi.      0
..                                                 ...    ...
970  I immediately said I wanted to talk to the man...      0
971                    The ambiance isn't much better.      0
972  Unfortunately, it only set us up for disapppoi...      0
973                              The food wasn't good.      0
974  Your servers suck, wait, correction, our serve...      0
975      What happened next was pretty....off putting.      0
976  too bad cause I know it's family owned, I real...      0
977               Overpriced for what you are getting.      0
978               I vomited in the bathroom mid lunch.      0
979  I kept looking at the time and it had soon bec...      0
980  I have been to very few places to eat that und...      0
981  We started with the tuna sashimi which was bro...      0
982                            Food was below average.      0
983  It sure does beat the nachos at the movies but...      0
984       All in all, Ha Long Bay was a bit of a flop.      0
985  The problem I have is that they charge $11.99 ...      0
986  Shrimp- When I unwrapped it (I live only 1/2 a...      0
987     It lacked flavor, seemed undercooked, and dry.      0
988  It really is impressive that the place hasn't ...      0
989  I would avoid this place if you are staying in...      0
990  The refried beans that came with my meal were ...      0
991         Spend your money and time some place else.      0
992  A lady at the table next to us found a live gr...      0
993            the presentation of the food was awful.      0
994           I can't tell you how disappointed I was.      0
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [3]:
import re
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
r,c =Data.shape
cleaned_text = []


[nltk_data] Downloading package stopwords to /home/aayush/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [4]:
for i in range(r):
    review = Data[i,0]
    review =          re.sub('[^a-zA-Z]' , ' ' , review).lower().split()
    ps = PorterStemmer()
    
    review =[ps.stem(word) for word in review if  word not in set(stopwords.words('english'))]
    review =' '.join(review)
    cleaned_text.append(review)
print("Cleaned Reviews")
pd.DataFrame(cleaned_text)

Cleaned Reviews


0
0                                       wow love place
1                                           crust good
2                                   tasti textur nasti
3    stop late may bank holiday rick steve recommen...
4                              select menu great price
5                              get angri want damn pho
6                                  honeslti tast fresh
7    potato like rubber could tell made ahead time ...
8                                            fri great
9                                          great touch
10                                       servic prompt
11                                       would go back
12        cashier care ever say still end wayyy overpr
13          tri cape cod ravoli chicken cranberri mmmm
14                      disgust pretti sure human hair
15                               shock sign indic cash
16                                    highli recommend
17                          waitress littl slow servic
18                      place worth time let alon vega
19                                                like
20                                       burritto blah
21                                           food amaz
22                                    servic also cute
23                     could care less interior beauti
24                                             perform
25               right red velvet cake ohhh stuff good
26                             never brought salad ask
27   hole wall great mexican street taco friendli s...
28   took hour get food tabl restaur food luke warm...
29                                worst salmon sashimi
..                                                 ...
970  immedi said want talk manag want talk guy shot...
971                                ambianc much better
972                  unfortun set us disapppoint entre
973                                          food good
974        server suck wait correct server heimer suck
975                             happen next pretti put
976    bad caus know famili own realli want like place
977                                         overpr get
978                           vomit bathroom mid lunch
979     kept look time soon becom minut yet still food
980      place eat circumst would ever return top list
981    start tuna sashimi brownish color obvious fresh
982                                        food averag
983  sure beat nacho movi would expect littl bit co...
984                               ha long bay bit flop
985  problem charg sandwich bigger subway sub offer...
986    shrimp unwrap live mile brushfir liter ice cold
987                     lack flavor seem undercook dri
988                         realli impress place close
989                       would avoid place stay mirag
990         refri bean came meal dri crusti food bland
991                         spend money time place els
992  ladi tabl next us found live green caterpillar...
993                                    present food aw
994                                    tell disappoint
995                      think food flavor textur lack
996                             appetit instantli gone
997                       overal impress would go back
998  whole experi underwhelm think go ninja sushi n...
999  wast enough life pour salt wound draw time too...

[1000 rows x 1 columns]

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
X = cv.fit_transform(cleaned_text).toarray()
y = np.array(Data[0:,1].astype(np.int64))

In [6]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X, y , test_size = 0.25 , random_state = 54)
y_train = y_train[:,0]
y_test = y_test[:,0]

In [7]:
print("Classification Model : Naive Bayes")
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)
y_pred1 = classifier.predict(X_test)


from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(y_test, y_pred1)
print(cm1)
print("No of correct = " + str(cm1[0,0] + cm1[1,1]) + "/250")
print("Accuracy = " + str((cm1[0,0] + cm1[1,1])/2.5))

Classification Model : Naive Bayes
[[ 69  52]
 [ 19 110]]
No of correct = 179/250
Accuracy = 71.6


In [8]:
print("Classification Model : SVM")
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear')
classifier.fit(X_train,y_train)

y_pred2 = classifier.predict(X_test)
cm2 = confusion_matrix(y_test, y_pred2)
print(cm2)
print("No of correct = " + str(cm2[0,0] + cm2[1,1]) + "/250")
print("Accuracy = " + str((cm2[0,0] + cm2[1,1])/2.5))

Classification Model : SVM
[[96 25]
 [31 98]]
No of correct = 194/250
Accuracy = 77.6


In [9]:
print("Classification Model : Logistic Regressuin")
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0 , solver = 'liblinear')
classifier.fit(X_train, y_train)

y_pred3 = classifier.predict(X_test)

cm3 = confusion_matrix(y_test, y_pred3)
print(cm3)
print("No of correct = " + str(cm3[0,0] + cm3[1,1]) + "/250")
print("Accuracy = " + str((cm3[0,0] + cm3[1,1])/2.5))

Classification Model : Logistic Regression
[[99 22]
 [30 99]]
No of correct = 198/250
Accuracy = 79.2


In [10]:
print("Classification Model : KNN")
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)
y_pred4 = classifier.predict(X_test)

cm4 = confusion_matrix(y_test, y_pred4)
print(cm4)
print("No of correct = " + str(cm4[0,0] + cm4[1,1]) + "/250")
print("Accuracy = " + str((cm4[0,0] + cm4[1,1])/2.5))

Classification Model : KNN
[[77 44]
 [50 79]]
No of correct = 156/250
Accuracy = 62.4
